### ISSUE TITLE
Explore options for anonymousUser

### ISSUE THREAD

**Issue by adatzer** [snowplow/snowplow-gtm-server-side-launchdarkly-tag#3]
As discussed [here](https://github.com/snowplow/snowplow-gtm-server-side-launchdarkly-tag/pull/2#discussion_r1142847226);

**Comment by InTheCloudDan** [comment]
@adatzer I'm from the LaunchDarkly ecosystem team, happy to hop on a call and talk through options.

**Comment by adatzer** [comment]
Hi @InTheCloudDan ! Thank you very much for proposing this!
Happy to hop on a call as well cc @igneel64 @jethron let's find out how we can connect!

**Comment by adatzer** [comment]
Closing this issue after the `0.3.0` release (even if a user wants to use `anonymousUser` as a randomization unit it would now be possible to add) .
